Repository replicatedhq/kots-lint, pull requests merged in 2023-04, with the labels that each got.

#146 Update kurlkinds to 1.3.3
  go.mod
  go.sum
Labels: type::chore

#148 add config validation linter
  go.mod
  go.sum
  kubernetes_json_schema/schema/v1.23.6-standalone-strict/config-kots-v1beta1.json
  pkg/kots/lint_helper_test.go
  pkg/kots/lint_test.go
  pkg/kots/rego/kots-spec-opa-nonrendered.rego
  pkg/kots/render.go
Labels: type::feature

#149 Allow datadog headers
  pkg/daemon/daemon.go
Labels: type::bug, bug::regression
