Repository replicatedhq/kots-lint, pull requests merged in 2023-06, with the labels that each got.

#159 add `invalid-rendered-yaml` linter
  Makefile
  go.mod
  go.sum
  okteto.Dockerfile
  pkg/kots/lint.go
  pkg/kots/lint_test.go
  pkg/kots/render.go
Labels: type::bug, bug::regression

#160 fix build
  Makefile
Labels: type::chore

#161 Linting for builders Helm charts
  README.md
  app.go
  go.mod
  go.sum
  pkg/daemon/daemon.go
  pkg/handlers/builders_lint.go
  pkg/kots/builders_lint.go
  pkg/kots/builders_lint_test.go
  pkg/kots/helm.go
  pkg/kots/lint.go
  pkg/kots/lint_test.go
  pkg/kots/rego/builders-opa.rego
  pkg/kots/test-data/builders/not-a-chart.tgz
  pkg/kots/test-data/builders/testchart-with-labels-16.2.2.tgz
  pkg/kots/test-data/builders/testchart-without-labels-16.2.2.tgz
  pkg/kots/test-data/builders/testchart-without-labels-with-preflight-16.2.3.tgz
Labels: type::feature
