Repository replicatedhq/kots-lint, pull requests merged in 2024-11, with the labels that each got.

#188 Fix okteto deploy error
  okteto-pipeline.yml
  okteto.yml
Labels: type::chore

#189 Allow long lines in YAML specs
  pkg/util/text.go
Labels: type::bug, bug::normal

#190 feat: return error if ec version is a pre-release
  go.mod
  go.sum
  pkg/ec/lint.go
  pkg/ec/lint_test.go
  pkg/version/version_test.go
Labels: type::feature
